In [1]:
import pandas as pd

In [6]:
import numpy as np

In [11]:
worldEd = pd.read_csv("C:/Users/lien0/Downloads/Table-11-Education-SOWC2021-EN.csv")
worldEd.head(25)

,TABLE 11. EDUCATION,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Countries and areas,Equitable access,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Out-of-school rate\n2013–2019 (R),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Literacy rate\n2019,NaN,NaN,NaN
3,NaN,One year before primary entry age,NaN,NaN,NaN,Primary education,NaN,NaN,NaN,Lower secondary education,...,NaN,NaN,Proportion of children at the end of lower sec...,NaN,NaN,NaN,Youth (15–24 years) literacy rate (%),NaN,NaN,NaN
4,NaN,Male,NaN,Female,NaN,Male,NaN,Female,NaN,Male,...,Math,NaN,Reading,NaN,Math,NaN,Male,NaN,Female,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Afghanistan,-,NaN,-,NaN,-,NaN,-,NaN,-,...,11,NaN,-,NaN,-,NaN,74,NaN,56,NaN
7,Albania,4,NaN,2,NaN,6,NaN,3,NaN,6,...,-,NaN,48,NaN,58,NaN,99,NaN,100,NaN
8,Algeria,-,NaN,-,NaN,-,NaN,-,NaN,-,...,-,NaN,21,NaN,19,NaN,98,NaN,97,NaN
9,Andorra,-,NaN,-,NaN,-,NaN,-,NaN,-,...,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN
10,Angola,31,NaN,39,NaN,-,NaN,-,NaN,-,...,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN
11,Anguilla,14,NaN,-,NaN,-,NaN,-,NaN,-,...,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN
12,Antigua and Barbuda,14,NaN,4,NaN,4,NaN,1,NaN,1,...,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN
13,Argentina,2,NaN,2,NaN,-,NaN,-,NaN,0,...,56,NaN,48,NaN,31,NaN,99,NaN,100,NaN
14,Armenia,52,NaN,50,NaN,9,NaN,9,NaN,11,...,55,NaN,-,NaN,50,NaN,-,NaN,-,NaN
15,Australia,13,NaN,14,NaN,0,NaN,0,NaN,2,...,64,NaN,80,NaN,78,NaN,-,NaN,-,NaN
16,Austria,0,NaN,0,NaN,0,NaN,0,NaN,1,...,-,NaN,76,NaN,79,NaN,-,NaN,-,NaN
17,Azerbaijan,32,NaN,19,NaN,10,NaN,7,NaN,0,...,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN
18,Bahamas,-,NaN,-,NaN,-,NaN,-,NaN,23,...,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN
19,Bahrain,31,NaN,28,NaN,2,NaN,3,NaN,7,...,-,NaN,-,NaN,39,NaN,100,NaN,99,NaN
20,Bangladesh,-,NaN,-,NaN,-,NaN,-,NaN,-,...,32,NaN,54,NaN,57,NaN,94,NaN,96,NaN
21,Barbados,6,NaN,10,NaN,1,NaN,2,NaN,7,...,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN
22,Belarus,0,NaN,4,NaN,1,NaN,2,NaN,1,...,-,NaN,77,NaN,71,NaN,100,NaN,100,NaN
23,Belgium,3,NaN,2,NaN,1,NaN,0,NaN,1,...,-,NaN,79,NaN,80,NaN,-,NaN,-,NaN
24,Belize,18,NaN,16,NaN,1,NaN,1,NaN,9,...,-,NaN,-,NaN,-,NaN,-,NaN,-,NaN

In [16]:
worldEd = worldEd.dropna(axis='columns', how = 'all')
worldEd = worldEd.dropna(axis='rows', how = 'all')
worldEd.head(25)

,TABLE 11. EDUCATION,Unnamed: 1,Unnamed: 3,Unnamed: 5,Unnamed: 7,Unnamed: 9,Unnamed: 11,Unnamed: 13,Unnamed: 15,Unnamed: 17,...,Unnamed: 25,Unnamed: 27,Unnamed: 29,Unnamed: 31,Unnamed: 33,Unnamed: 35,Unnamed: 37,Unnamed: 39,Unnamed: 41,Unnamed: 43
1,Countries and areas,Equitable access,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Completion,...,NaN,NaN,Learning,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Out-of-school rate\n2013–2019 (R),NaN,NaN,NaN,NaN,NaN,NaN,NaN,Completion rate\n2010–2019 (R),...,NaN,NaN,Learning outcomes\n2013–2019 (R),NaN,NaN,NaN,NaN,NaN,Literacy rate\n2019,NaN
3,NaN,One year before primary entry age,NaN,Primary education,NaN,Lower secondary education,NaN,Upper secondary education,NaN,Primary education,...,Upper secondary education,NaN,Proportion of children in grade 2 or 3 achievi...,NaN,Proportion of children at the end of primary a...,NaN,Proportion of children at the end of lower sec...,NaN,Youth (15–24 years) literacy rate (%),NaN
4,NaN,Male,Female,Male,Female,Male,Female,Male,Female,Male,...,Male,Female,Reading,Math,Reading,Math,Reading,Math,Male,Female
6,Afghanistan,-,-,-,-,-,-,44,69,67,...,32,14,22,25,13,11,-,-,74,56
7,Albania,4,2,6,3,6,1,21,15,94,...,76,80,-,-,-,-,48,58,99,100
8,Algeria,-,-,-,-,-,-,-,-,93,...,22,37,-,-,-,-,21,19,98,97
9,Andorra,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
10,Angola,31,39,-,-,-,-,-,-,63,...,24,15,-,-,-,-,-,-,-,-
11,Anguilla,14,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
12,Antigua and Barbuda,14,4,4,1,1,2,14,12,-,...,-,-,-,-,-,-,-,-,-,-
13,Argentina,2,2,-,-,0,0,15,7,91,...,46,53,76,71,46,56,48,31,99,100
14,Armenia,52,50,9,9,11,9,16,4,99,...,69,79,-,-,-,55,-,50,-,-
15,Australia,13,14,0,0,2,3,10,6,-,...,-,-,94,70,-,64,80,78,-,-
16,Austria,0,0,0,0,1,0,10,9,-,...,-,-,-,-,98,-,76,79,-,-
17,Azerbaijan,32,19,10,7,0,0,0,0,-,...,-,-,-,-,81,-,-,-,-,-
18,Bahamas,-,-,-,-,23,21,29,24,-,...,-,-,-,-,-,-,-,-,-,-
19,Bahrain,31,28,2,3,7,0,18,6,-,...,-,-,69,40,-,-,-,39,100,99
20,Bangladesh,-,-,-,-,-,-,41,36,76,...,32,27,47,34,44,32,54,57,94,96
21,Barbados,6,10,1,2,7,3,7,3,99,...,91,97,-,-,-,-,-,-,-,-
22,Belarus,0,4,1,2,1,1,6,4,100,...,91,94,-,-,-,-,77,71,100,100
23,Belgium,3,2,1,0,1,1,1,2,-,...,-,-,-,-,-,-,79,80,-,-
24,Belize,18,16,1,1,9,11,38,35,95,...,48,51,-,-,-,-,-,-,-,-
25,Benin,15,16,3,10,27,43,46,66,51,...,12,5,9,34,23,11,-,-,70,52
26,Bhutan,58,59,5,2,18,6,33,22,67,...,25,18,-,-,-,-,56,-,-,-

In [18]:
worldEd.fillna('', inplace=True)
worldEd.head(25)

,TABLE 11. EDUCATION,Unnamed: 1,Unnamed: 3,Unnamed: 5,Unnamed: 7,Unnamed: 9,Unnamed: 11,Unnamed: 13,Unnamed: 15,Unnamed: 17,...,Unnamed: 25,Unnamed: 27,Unnamed: 29,Unnamed: 31,Unnamed: 33,Unnamed: 35,Unnamed: 37,Unnamed: 39,Unnamed: 41,Unnamed: 43
1,Countries and areas,Equitable access,,,,,,,,Completion,...,,,Learning,,,,,,,
2,,Out-of-school rate\n2013–2019 (R),,,,,,,,Completion rate\n2010–2019 (R),...,,,Learning outcomes\n2013–2019 (R),,,,,,Literacy rate\n2019,
3,,One year before primary entry age,,Primary education,,Lower secondary education,,Upper secondary education,,Primary education,...,Upper secondary education,,Proportion of children in grade 2 or 3 achievi...,,Proportion of children at the end of primary a...,,Proportion of children at the end of lower sec...,,Youth (15–24 years) literacy rate (%),
4,,Male,Female,Male,Female,Male,Female,Male,Female,Male,...,Male,Female,Reading,Math,Reading,Math,Reading,Math,Male,Female
6,Afghanistan,-,-,-,-,-,-,44,69,67,...,32,14,22,25,13,11,-,-,74,56
7,Albania,4,2,6,3,6,1,21,15,94,...,76,80,-,-,-,-,48,58,99,100
8,Algeria,-,-,-,-,-,-,-,-,93,...,22,37,-,-,-,-,21,19,98,97
9,Andorra,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
10,Angola,31,39,-,-,-,-,-,-,63,...,24,15,-,-,-,-,-,-,-,-
11,Anguilla,14,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
12,Antigua and Barbuda,14,4,4,1,1,2,14,12,-,...,-,-,-,-,-,-,-,-,-,-
13,Argentina,2,2,-,-,0,0,15,7,91,...,46,53,76,71,46,56,48,31,99,100
14,Armenia,52,50,9,9,11,9,16,4,99,...,69,79,-,-,-,55,-,50,-,-
15,Australia,13,14,0,0,2,3,10,6,-,...,-,-,94,70,-,64,80,78,-,-
16,Austria,0,0,0,0,1,0,10,9,-,...,-,-,-,-,98,-,76,79,-,-
17,Azerbaijan,32,19,10,7,0,0,0,0,-,...,-,-,-,-,81,-,-,-,-,-
18,Bahamas,-,-,-,-,23,21,29,24,-,...,-,-,-,-,-,-,-,-,-,-
19,Bahrain,31,28,2,3,7,0,18,6,-,...,-,-,69,40,-,-,-,39,100,99
20,Bangladesh,-,-,-,-,-,-,41,36,76,...,32,27,47,34,44,32,54,57,94,96
21,Barbados,6,10,1,2,7,3,7,3,99,...,91,97,-,-,-,-,-,-,-,-
22,Belarus,0,4,1,2,1,1,6,4,100,...,91,94,-,-,-,-,77,71,100,100
23,Belgium,3,2,1,0,1,1,1,2,-,...,-,-,-,-,-,-,79,80,-,-
24,Belize,18,16,1,1,9,11,38,35,95,...,48,51,-,-,-,-,-,-,-,-
25,Benin,15,16,3,10,27,43,46,66,51,...,12,5,9,34,23,11,-,-,70,52
26,Bhutan,58,59,5,2,18,6,33,22,67,...,25,18,-,-,-,-,56,-,-,-

In [20]:
sowc = pd.read_csv("C:/Users/lien0/Downloads/SOWC-Statistical-tables-ALL-2021-EN.csv")
sowc.head(25)

,TABLE 13. SOCIAL PROTECTION AND EQUITY,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Countries and areas,Mothers with newborns receiving cash benefit (...,Proportion of children covered by social prote...,NaN,Distribution of social protection benefits (%)...,NaN,NaN,Share of household income (%)\n2010–2019 (R),NaN,NaN,Gini Coefficient\n2010–2019 (R),Palma Index of income inequality\n2010–2019 (R),VMIR (vast majority income ratio)\n2010–2019 (R),GDP per capita (current US$)\n2010–2019 (R)
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,Bottom 40%,Top 20%,Bottom 20%,Bottom 40%,Top 20%,Bottom 20%,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Afghanistan,1.7,0.4,NaN,-,-,-,-,-,-,31.0,-,-,507
6,Albania,-,-,NaN,45.9,13.7,27.6,19.5,40.7,7.5,33.2,1.3,0.8,"5,353"
7,Algeria,11.2,-,NaN,-,-,-,23.1,37.2,9.4,27.6,1.0,0.8,"3,974"
8,Andorra,-,-,NaN,-,-,-,-,-,-,28.0,1.0,-,"40,886"
9,Angola,-,-,NaN,-,-,-,11.5,55.6,3.8,51.3,3.5,0.6,"2,791"
10,Anguilla,73.3,2.0,NaN,-,-,-,-,-,-,-,-,-,-
11,Antigua and Barbuda,37.0,-,NaN,-,-,-,-,-,-,-,-,-,"17,113"
12,Argentina,31.7,79.6,NaN,74.8,5.5,48.6,14.2,47.9,4.7,42.5,2.1,0.7,"9,912"
13,Armenia,61.6,30.2,NaN,58.3,9.1,35.9,22.2,39.1,9.0,34.4,1.4,0.7,"4,623"
14,Australia,100.0,100.0,NaN,-,-,-,19.6,42.1,7.4,32.5,1.3,0.7,"55,057"
15,Austria,100.0,100.0,NaN,-,-,-,20.9,38.7,7.9,27.5,1.0,0.8,"50,122"
16,Azerbaijan,16.0,16.9,NaN,29.0,32.9,17.4,-,-,-,26.6,0.7,0.8,"4,793"
17,Bahamas,46.5,-,NaN,-,-,-,-,-,-,41.4,2.0,-,"34,864"
18,Bahrain,-,56.7,NaN,-,-,-,-,-,-,59.6,-,-,"23,504"
19,Bangladesh,20.9,29.4,NaN,44.4,18.0,24.3,21.0,41.4,8.6,48.3,2.9,0.7,"1,856"
20,Barbados,-,-,NaN,-,-,-,-,-,-,32.0,3.1,-,"18,148"
21,Belarus,100.0,-,NaN,50.4,16.6,27.1,24.3,35.4,10.0,25.2,0.9,0.8,"6,698"
22,Belgium,100.0,100.0,NaN,-,-,-,23.2,36.4,8.9,25.1,0.9,0.8,"46,345"
23,Belize,19.9,3.0,NaN,-,-,-,-,-,-,53.3,3.9,0.5,"4,815"
24,Benin,41.0,11.6,NaN,-,-,-,12.8,52.1,3.2,47.8,2.9,0.6,"1,219"

In [21]:
soxc = sowc.dropna(axis='columns', how = 'all')
sowc = sowc.dropna(axis='rows', how = 'all')
sowc.head(25)

,TABLE 13. SOCIAL PROTECTION AND EQUITY,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
1,Countries and areas,Mothers with newborns receiving cash benefit (...,Proportion of children covered by social prote...,NaN,Distribution of social protection benefits (%)...,NaN,NaN,Share of household income (%)\n2010–2019 (R),NaN,NaN,Gini Coefficient\n2010–2019 (R),Palma Index of income inequality\n2010–2019 (R),VMIR (vast majority income ratio)\n2010–2019 (R),GDP per capita (current US$)\n2010–2019 (R)
3,NaN,NaN,NaN,NaN,Bottom 40%,Top 20%,Bottom 20%,Bottom 40%,Top 20%,Bottom 20%,NaN,NaN,NaN,NaN
5,Afghanistan,1.7,0.4,NaN,-,-,-,-,-,-,31.0,-,-,507
6,Albania,-,-,NaN,45.9,13.7,27.6,19.5,40.7,7.5,33.2,1.3,0.8,"5,353"
7,Algeria,11.2,-,NaN,-,-,-,23.1,37.2,9.4,27.6,1.0,0.8,"3,974"
8,Andorra,-,-,NaN,-,-,-,-,-,-,28.0,1.0,-,"40,886"
9,Angola,-,-,NaN,-,-,-,11.5,55.6,3.8,51.3,3.5,0.6,"2,791"
10,Anguilla,73.3,2.0,NaN,-,-,-,-,-,-,-,-,-,-
11,Antigua and Barbuda,37.0,-,NaN,-,-,-,-,-,-,-,-,-,"17,113"
12,Argentina,31.7,79.6,NaN,74.8,5.5,48.6,14.2,47.9,4.7,42.5,2.1,0.7,"9,912"
13,Armenia,61.6,30.2,NaN,58.3,9.1,35.9,22.2,39.1,9.0,34.4,1.4,0.7,"4,623"
14,Australia,100.0,100.0,NaN,-,-,-,19.6,42.1,7.4,32.5,1.3,0.7,"55,057"
15,Austria,100.0,100.0,NaN,-,-,-,20.9,38.7,7.9,27.5,1.0,0.8,"50,122"
16,Azerbaijan,16.0,16.9,NaN,29.0,32.9,17.4,-,-,-,26.6,0.7,0.8,"4,793"
17,Bahamas,46.5,-,NaN,-,-,-,-,-,-,41.4,2.0,-,"34,864"
18,Bahrain,-,56.7,NaN,-,-,-,-,-,-,59.6,-,-,"23,504"
19,Bangladesh,20.9,29.4,NaN,44.4,18.0,24.3,21.0,41.4,8.6,48.3,2.9,0.7,"1,856"
20,Barbados,-,-,NaN,-,-,-,-,-,-,32.0,3.1,-,"18,148"
21,Belarus,100.0,-,NaN,50.4,16.6,27.1,24.3,35.4,10.0,25.2,0.9,0.8,"6,698"
22,Belgium,100.0,100.0,NaN,-,-,-,23.2,36.4,8.9,25.1,0.9,0.8,"46,345"
23,Belize,19.9,3.0,NaN,-,-,-,-,-,-,53.3,3.9,0.5,"4,815"
24,Benin,41.0,11.6,NaN,-,-,-,12.8,52.1,3.2,47.8,2.9,0.6,"1,219"
25,Bhutan,10.4,13.5,NaN,-,-,-,17.5,44.4,6.7,37.4,1.6,0.7,"3,316"
26,Bolivia (Plurinational State of),59.3,66.2,NaN,42.7,24.5,25.1,15.4,47.3,5.1,43.0,2.2,0.6,"3,552"
27,Bosnia and Herzegovina,100.0,-,NaN,36.5,24.7,16.5,19.8,40.7,7.5,33.0,1.3,0.7,"6,109"

In [22]:
sowc.fillna('', inplace=True)
sowc.head(25)

,TABLE 13. SOCIAL PROTECTION AND EQUITY,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
1,Countries and areas,Mothers with newborns receiving cash benefit (...,Proportion of children covered by social prote...,,Distribution of social protection benefits (%)...,,,Share of household income (%)\n2010–2019 (R),,,Gini Coefficient\n2010–2019 (R),Palma Index of income inequality\n2010–2019 (R),VMIR (vast majority income ratio)\n2010–2019 (R),GDP per capita (current US$)\n2010–2019 (R)
3,,,,,Bottom 40%,Top 20%,Bottom 20%,Bottom 40%,Top 20%,Bottom 20%,,,,
5,Afghanistan,1.7,0.4,,-,-,-,-,-,-,31.0,-,-,507
6,Albania,-,-,,45.9,13.7,27.6,19.5,40.7,7.5,33.2,1.3,0.8,"5,353"
7,Algeria,11.2,-,,-,-,-,23.1,37.2,9.4,27.6,1.0,0.8,"3,974"
8,Andorra,-,-,,-,-,-,-,-,-,28.0,1.0,-,"40,886"
9,Angola,-,-,,-,-,-,11.5,55.6,3.8,51.3,3.5,0.6,"2,791"
10,Anguilla,73.3,2.0,,-,-,-,-,-,-,-,-,-,-
11,Antigua and Barbuda,37.0,-,,-,-,-,-,-,-,-,-,-,"17,113"
12,Argentina,31.7,79.6,,74.8,5.5,48.6,14.2,47.9,4.7,42.5,2.1,0.7,"9,912"
13,Armenia,61.6,30.2,,58.3,9.1,35.9,22.2,39.1,9.0,34.4,1.4,0.7,"4,623"
14,Australia,100.0,100.0,,-,-,-,19.6,42.1,7.4,32.5,1.3,0.7,"55,057"
15,Austria,100.0,100.0,,-,-,-,20.9,38.7,7.9,27.5,1.0,0.8,"50,122"
16,Azerbaijan,16.0,16.9,,29.0,32.9,17.4,-,-,-,26.6,0.7,0.8,"4,793"
17,Bahamas,46.5,-,,-,-,-,-,-,-,41.4,2.0,-,"34,864"
18,Bahrain,-,56.7,,-,-,-,-,-,-,59.6,-,-,"23,504"
19,Bangladesh,20.9,29.4,,44.4,18.0,24.3,21.0,41.4,8.6,48.3,2.9,0.7,"1,856"
20,Barbados,-,-,,-,-,-,-,-,-,32.0,3.1,-,"18,148"
21,Belarus,100.0,-,,50.4,16.6,27.1,24.3,35.4,10.0,25.2,0.9,0.8,"6,698"
22,Belgium,100.0,100.0,,-,-,-,23.2,36.4,8.9,25.1,0.9,0.8,"46,345"
23,Belize,19.9,3.0,,-,-,-,-,-,-,53.3,3.9,0.5,"4,815"
24,Benin,41.0,11.6,,-,-,-,12.8,52.1,3.2,47.8,2.9,0.6,"1,219"
25,Bhutan,10.4,13.5,,-,-,-,17.5,44.4,6.7,37.4,1.6,0.7,"3,316"
26,Bolivia (Plurinational State of),59.3,66.2,,42.7,24.5,25.1,15.4,47.3,5.1,43.0,2.2,0.6,"3,552"
27,Bosnia and Herzegovina,100.0,-,,36.5,24.7,16.5,19.8,40.7,7.5,33.0,1.3,0.7,"6,109"